version: '3.8'

services:
  sportradar-api:
    build:
      context: .
      dockerfile: src/Sportradar.Service.Api/Dockerfile
    container_name: sportradar-api
    restart: unless-stopped
    ports:
      - "7100:80"
      - "7101:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - PathBase=/
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sportradar-service-network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=sportradar
      - POSTGRES_USER=sportradar
      - POSTGRES_PASSWORD=sportradar
    ports:
      - "5432:5432"
    networks:
      - sportradar-service-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sportradar -d sportradar"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "7200:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sportradar-service-network

networks:
  sportradar-service-network:
    driver: bridge

volumes:
  postgres_data: